name: Tests / E2E Fork
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths-ignore:
      - "docs/**"
      - "**.md"
      - "LICENSE"

jobs:
  # dynamically build a matrix of test/test suite pairs to run
  build-test-matrix:
    if: ${{ github.event.pull_request.head.repo.fork || github.actor == 'dependabot[bot]' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: 1.19
      - id: set-matrix
        run: echo "matrix=$(go run cmd/build_test_matrix/main.go)" >> $GITHUB_OUTPUT
        env:
          TEST_EXCLUSIONS: "TestInterTxTestSuite,TestIncentivizedInterTxTestSuite,TestUpgradeTestSuite"

  e2e:
    env:
      CHAIN_A_TAG: latest
      CHAIN_B_TAG: latest
      CHAIN_IMAGE: ibc-go-simd
    if: ${{ github.event.pull_request.head.repo.fork || github.actor == 'dependabot[bot]' || github.event_name == 'workflow_dispatch' }}
    needs:
      - build-test-matrix
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.build-test-matrix.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v3
      - name: Docker Build
        run: docker build . -t "${CHAIN_IMAGE}:${CHAIN_A_TAG}" --build-arg IBC_GO_VERSION=latest
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.19
      - name: Run e2e Test
        run: |
          cd e2e
          make e2e-test test=${{ matrix.test }}
